# Generated by Django 2.0 on 2021-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fabric', models.CharField(max_length=65, verbose_name='Nome do Tecido')),
                ('available_fabric', models.CharField(choices=[('dis', 'DISPONIVEL'), ('ndis', 'NÃO DISPONIVEL')], default='dis', max_length=30, verbose_name='Status do Tecido')),
            ],
            options={
                'verbose_name_plural': 'Tecidos',
                'verbose_name': 'Tecido',
            },
        ),
    ]
