# Generated by Django 2.0 on 2021-04-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductType',
        ),
    ]
