# Generated by Django 2.0 on 2021-04-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210420_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=65, verbose_name='Nome do Produto')),
                ('available_product', models.CharField(choices=[('dis', 'DISPONIVEL'), ('ndis', 'NÃO DISPONIVEL')], default='dis', max_length=30, verbose_name='Status do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Fabric',
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Tipo do Produto', 'verbose_name_plural': 'Tipo dos Produtos'},
        ),
    ]
