# Generated by Django 2.0 on 2021-04-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210420_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(related_name='product_type', to='app.ProductType', verbose_name='Tipo do Produto'),
        ),
    ]
