# Generated by Django 2.0 on 2021-04-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_type', to='app.ProductType', verbose_name='Tipo do Produto'),
        ),
    ]
