# Generated by Django 2.0 on 2021-04-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210420_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fabric', models.CharField(max_length=30, verbose_name='Nome do Tecido')),
                ('type_fabric', models.CharField(choices=[('inf', 'INFORMAR'), ('lis', 'LISA'), ('cos', 'COM ESTAMPA')], default='inf', max_length=30, verbose_name='Tipo do tecido')),
                ('available_fabric', models.CharField(choices=[('dis', 'DISPONIVEL'), ('ndis', 'NÃO DISPONIVEL')], default='dis', max_length=30, verbose_name='Status do Tecido')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição do Tecido')),
            ],
            options={
                'verbose_name': 'Tecido',
                'verbose_name_plural': 'Tecidos',
            },
        ),
    ]
