# Generated by Django 2.0 on 2021-04-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fabric_picture_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='cod_fabric',
            field=models.CharField(default=1, editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
